language:
  - cpp

dist:
 - bionic

os:
- linux

compiler:
  - gcc

addons:
    apt:
      packages:
        - cmake
        - cmake-data
        - libxerces-c-dev
        - libboost-all-dev
        - freeglut3-dev


script:
  - mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release
  - cmake --build . --target pmuc --config Release -- -j4
  - ctest -C Release --output-on-failure

